version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pimaldaumen
    volumes:
      - ~/ws/postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '8079:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/data-fetching
    links:
      - db
