version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pimaldaumen
    volumes:
      - ~/ws/postgres-data:/var/lib/postgresql/data
